# Assumes UI repo is cloned in parent directory
version: '2'
services:
  api:
    build: .
  ui:
    build:
      context: ../hmda-platform-ui
      args:
        dev: build:docker
    ports:
      - "80:80"
    depends_on:
      - api
    volumes:
      - ../hmda-platform-ui/dist:/usr/src/app/dist
