apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Release.Name }}-inst-api-config"
data:
  postgres.create-schema: "{{ .Values.postgresql.createSchema }}"
  postgres.ssl: "{{ .Values.postgresql.ssl }}"
  postgres.user:  "{{ .Values.postgresql.postgresUser }}"
  postgres.database: "{{ .Values.postgresql.postgresDatabase }}"
  cassandra-hosts: "{{ .Values.cassandra.hosts }}"
