apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "institutions-api.fullname" . }}
  labels:
    app: {{ template "institutions-api.name" . }}
    chart: {{ template "institutions-api.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "institutions-api.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "institutions-api.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            limits:
              cpu: "6"
              memory: "3200Mi"
          env:
            - name: PG_HOST
              valueFrom:
                secretKeyRef:
                  name: inst-postgres-credentials
                  key: host
            - name: PG_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: "{{ .Release.Name }}-inst-api-config"
                  key: postgres.database
            - name: PG_USER
              valueFrom:
                secretKeyRef:
                  name: inst-postgres-credentials
                  key: username
            - name: PG_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: inst-postgres-credentials
                  key: password
            - name: PG_SSL
              valueFrom:
                configMapKeyRef:
                  name: "{{ .Release.Name }}-inst-api-config"
                  key: postgres.ssl
            - name: INSTITUTION_PG_CREATE_SCHEMA
              valueFrom:
                configMapKeyRef:
                  name: "{{ .Release.Name }}-inst-api-config"
                  key: postgres.create-schema
            - name: KAFKA_CLUSTER_HOSTS
              valueFrom:
                configMapKeyRef:
                  name: kafka-configmap
                  key: kafka.hosts
            - name: CASSANDRA_CLUSTER_HOSTS
              valueFrom:
                configMapKeyRef:
                  name: "{{ .Release.Name }}-inst-api-config"
                  key: cassandra-hosts
            - name: CASSANDRA_CLUSTER_USERNAME
              valueFrom:
                secretKeyRef:
                  name: cassandra-credentials
                  key: cassandra.username
            - name: CASSANDRA_CLUSTER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: cassandra-credentials
                  key: cassandra.password
            - name: JDBC_URL
              valueFrom:
                secretKeyRef:
                  name: inst-postgres-credentials
                  key: url
          ports:
            - name: {{ .Values.service.name }}
              containerPort: 9092
              protocol: {{ .Values.service.protocol }}
          livenessProbe:
            httpGet:
              path: /
              port: {{ .Values.service.port }}
          readinessProbe:
            httpGet:
              path: /
              port: {{ .Values.service.port }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
